"""Add attack_timeline and was_attempted

Revision ID: 4eaf96fed078
Revises: a6ce34d66a72
Create Date: 2026-03-19 21:38:42.255757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eaf96fed078'
down_revision: Union[str, None] = 'a6ce34d66a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('was_attempted', sa.Boolean(), nullable=True))
    op.alter_column('findings', 'fix_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_findings_scan_id', table_name='findings')
    op.add_column('scans', sa.Column('attack_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'attack_timeline')
    op.create_index('idx_findings_scan_id', 'findings', ['scan_id'], unique=False)
    op.alter_column('findings', 'fix_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('findings', 'was_attempted')
    # ### end Alembic commands ###
