"""Add IDE tables

Revision ID: 85c00f72fb72
Revises: g002_add_findings_missing_cols
Create Date: 2026-03-21 16:37:56.802742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85c00f72fb72'
down_revision: Union[str, None] = 'g002_add_findings_missing_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ide_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('clone_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('file_tree', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_contents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ide_file_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('annotation_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('quick_fix', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ide_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('findings', sa.Column('attack_name', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('quick_fix', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('money_loss_min', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('money_loss_max', sa.Integer(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('findings', 'money_loss_max')
    op.drop_column('findings', 'money_loss_min')
    op.drop_column('findings', 'quick_fix')
    op.drop_column('findings', 'attack_name')
    op.drop_table('ide_file_annotations')
    op.drop_table('ide_sessions')
    # ### end Alembic commands ###
